print('Simple statements')
print('+', '-', '*', '/')
print("len('abc')")
print("'abc'.upper()")
print("[x for x in range(10)")
print("import sys")
print(" tag = 1", "tag += 1")
print()
print('Combined statements')
print("def fun(): return True")
print("class MyClass(object): pass")
print("if a != b: print('True') else print('False')")
print("for x in range(10): print(x)")
print("while x < 10: print(s); x += 1")
