import sys
print(len(dir(sys)))
print(sys.api_version)
print(sys.argv)
print(sys.base_exec_prefix)
print(sys.builtin_module_names)
print(sys.byteorder)
print(sys.dont_write_bytecode)
print(sys.exc_info())
print(sys._home)
print(sys.executable)
print(sys.float_info)
print(sys.int_info)
print(sys.getcheckinterval())
print(sys.getdefaultencoding())
print(sys.getfilesystemencoding())
print(sys.getprofile())
print(sys.getrecursionlimit())
print(sys.getrefcount(1))
print(sys.getsizeof(int))
print(sys.getsizeof(1))
print(sys.getwindowsversion())
print(sys.maxsize)
print(sys.path)
print(sys.platform)
print(sys.stdin)
print(sys.stdout)
print(sys.float_repr_style)
print(sys.version_info)

import os
print(len(dir(os)))
print(os.altsep)
print(os.getcwd())
print(os.getenv('PATH'))
print(os.getpid())
print(os.getppid())
print(os.listdir(r'c:\texlive'))
print(os.name)
print(os.path.devnull)
print(os.path.exists(r'c:\texlive'))
print(os.path.join('a', 'b', 'c'))
print(os.path.split(r'a\b\c'))
#print([(root, dirs, files) for (root, dirs, files) in os.walk(r'c:\texlive')])



